Refactorized the code
middlewares/access-log pull request #9
Opened 2017-04-04 17:46 UTC by oscarotero

This change uses `strtr` instead `sprintf` to generate the messages, providing more flexibility to customize the output format.
It also fixes some bugs like append the uri's query to the path or replace `%h` value (ip) by `%v` (virtual host) instead prepend it.

2017-04-04 19:47 UTC, ajgarlag requested changes

2017-04-04 19:47 UTC, ajgarlag commented on src/AccessLog.php
> +        $message = $this->vhost ? '%v' : '%h';
Vhost info should not substitute the IP info, it should prepend it.

2017-04-04 19:50 UTC, oscarotero commented on src/AccessLog.php
> +        $message = $this->vhost ? '%v' : '%h';
the example in https://httpd.apache.org/docs/2.4/logs.html#accesslog (Section "Virtual Hosts") contains the following format:
```
LogFormat "%v %l %u %t \"%r\" %>s %b" comonvhost
```

2017-04-05 06:39 UTC, ajgarlag commented on src/AccessLog.php
> +        $message = $this->vhost ? '%v' : '%h';
I see. I'm interested in `vhost_combined` format defined in debian package: https://anonscm.debian.org/cgit/pkg-apache/apache2.git/tree/debian/config-dir/apache2.conf?h=jessie#n206

2017-04-06 19:34 UTC, merged